### PR TITLE
🔥 Upgrade to .NET 6

### PR DESCRIPTION
**Pull request by JosunLP**

### CODE REVIEW

**Comment by nikeee** [comment]
Any benefits from upgrading to .NET6 besides the syntactic sugar that C# 10 offers?

**Comment by JosunLP** [comment]
Better and safer binary files, much (!!!) faster, 100% cross-platform compatible, easier to update to the following .NET versions, hot reload in development, Open Telemetry and Dotnet monitor support, support for OpenSSL, the ChaCha20Poly1305 encryption scheme, and runtime defense-in-depth mitigations, obviously the syntactic sugar of C# 10 and I'm sure there are more.

**Comment by JosunLP** [comment]
Ahh yes, also global usings xD

**Comment by JosunLP** [comment]
Also, as far i can see, there is only one other open PR, it should be possible to merge that changes

**Comment by nikeee** [comment]
> Also, there is only one other open PR 

There is an entire branch that adds SSH support that is still up for merge.

> Better and safer binary files, much (!!!) faster, 100% cross-platform compatible, easier to update to the following .NET versions, hot reload in development, Open Telemetry and Dotnet monitor support, support for OpenSSL, the ChaCha20Poly1305 encryption scheme, and runtime defense-in-depth mitigations, global usings, obviously the syntactic sugar of C# 10 and I'm sure there are more.

Well yes, but which of these new things are the things that this library really benefits from? It's a library, so if the using application uses .NET 6, they'll have these benefits in the library, even if this library is not compiled against .NET 6 (or are there IL changes that would make it so?).

On the other side, raising the .NET target would require all users to upgrade too, which is not possible in every scenario. So we should only upgrade if there is some clear benefit.

**Comment by JosunLP** [comment]
Initially, .NET 6 is recommended. Every new project is set up as .NET 6 by default. Therefore, due to the (far to) old version, the library cannot currently be used in modern and secure .NET apps. Staying behind .NET development and not upgrading means that this library becomes a relic that is needed in modern apps but cannot be used. As the .NET system does not stop evolving and support for older versions ends, users are forced to upgrade.

**Comment by nikeee** [comment]
> the library cannot currently be used in modern and secure .NET apps

Are you _unable to_ use this library in .NET 6 applications in its current state?

**Comment by MaximilianAst** [comment]
Well sticking to netstandard doesnt mean for me to staying behind. Upgrading to net6 just locks out all users which are using it in a net48 application which is still supported by MS. And also keep in mind it is a library not an application. I agree on the application part that you should be on net6 sooner than later, but for libraries thats a different discussion.

**Pull request closed without merging**
